### ISSUE TITLE
Graql Delete queries should accept statements

### ISSUE THREAD

**Issue by haikalpribadi** [graknlabs/graql#115]
## Problem to Solve

This issue actually addresses several issues.

1) The ability to remove `attributes` from its owners without deleting the `attribute` itself
2) The ability to remove `roleplayers` from a relation

## Current Workaround

1) In order to delete an `attribute` from its owners right now uses the `via` keyword.
    ```
    match $x isa person, has name $n via $h; delete $h;
    ```
    However, we will be removing the `via` keyword, as we will be deleting the implicit relation that exists to implement the `has` keyword. Instead, we will have native `has` data structure.

2) Right now, there is no workaround to remove a `roleplayer` from a `relation` and this is actually a long-standing issue: #39.

## Proposed Solution

Allow the delete query to operate on full `statements`, just like insert `statements`. For example, here's an insert query operating on a `statement`:
```
match $x isa person; insert $x has name "alice";
```
A delete query operating on a `statement` can therefore do:
```
match $x isa person, has name $n; delete $x has name $n;
```
This will result in symmetry of `insert` and `delete` queries.

The above example shows how we solve the first problem - removing `attributes` from their owners`. In order to delete `roleplayers` from their relation, you can write
```
match $r (role-a: $x, role-b: $x) isa relation; 
delete $r (role-a: $x);
```

Note that in the examples above, we are not deleting the concept instances represented by the variables themselves. In order to delete the concept instances, you must write:
```
match $x isa person, has name $n;
delete $x isa person; $n isa name;
```
This will delete all instances of `person` and `name` found in the matched `pattern`.

### Concretely, the following will be implemented:

* we only allow `match...delete` queries (`delete...` only clauses are disallowed in the grammar)
* variables in the `delete` clause must be a subset of the `match` clause
* allowed deletion statements will by the same set allowed by `insert`
* as with inserts, using NEQ, Predicates (ie. operations) and ID properties in the `delete` clause should throw
* To verify that the concepts found in the `match` clause satisfy the `delete` clause as well: this means we can satisfy inheritance contraints naturally and throw otherwise, for example in :
```
match $x isa thing;
delete $x isa person;
```
however, the following will never throw:
```
match $x isa person;
delete $x isa thing;
```
* Deletion with ID edge case:
```
match $x id V123;
delete $x isa thing;
```
should work, however:
    * willl throw if V123 happens to be  a type
    * _requires_ the `isa thing` clause to delete the instance
    * will if trying to write `match $x id V123; delete $x id V123;`
* Note that as with `insert` statements, users can easily end up with quadratic complexities, such as:
```
match $x isa person; $n isa name;
delete $x has name $n;
```

* Deleting duplicate role players:
we will define that in delete queries:
```
match $r (arole: $x) isa reflexive;
delete $r (arole: $x); $r (arole: $x);
```
should be equivalent to :
```
match $r (arole: $x) isa reflexive;
delete $r (arole: $x, arole: $x);
```
this should lend itself to a straightforward implementation of executing one delete operation per property

## Additional Information

Implementing the proposed solution above would allow us to introduce an "update query", by doing:
```
match $x isa person, has first-name "alice", has last-name $n; 
delete $x has last-name $n;
insert $x has last-name "Davidson";
```

## Pieces of Work

- [x] update grammar (https://github.com/graknlabs/graql/pull/118)
- [x] modify grakn executors to handle statements (https://github.com/graknlabs/grakn/pull/5690) (https://github.com/graknlabs/grakn/pull/5712)
- [x] prepare documentation (https://github.com/graknlabs/docs/pull/296)
- [x] remove `via` keyword, and propagage (https://github.com/graknlabs/graql/pull/124) (https://github.com/graknlabs/graql/pull/125)
- [x] update internal clients and users of delete as required
- [x] delete BDD (https://github.com/graknlabs/grakn/pull/5711)  (https://github.com/graknlabs/verification/pull/38)

**Comment by flyingsilverfin** [comment]
Completed!
