### ISSUE TITLE
Since Update to Grakn 2.0: "matching given type without subtypes"

### ISSUE THREAD

**Issue by hkuich** [graknlabs/graql#192]
## Description

According to the documentation, this should work:

```GraqlMatch.Filtered getQuery = Graql.match(var("a").type("attribute_label")).get("a");```

however, I get:

```[GQL10] Graql Error: The variable '$a' is out of scope of the query```

## Environment

1. Mac OS 10.15.7
2. grakn core 2.0
3. client-java 2.0.0-alpha-4

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. insert any attribute type into grakn 2.0
2. perform above query using client-java

**Comment by haikalpribadi** [comment]
This issue is now fixed in: https://github.com/graknlabs/graql/commit/4b340c2ac7b73456d96bb48ad89aadc043d9eab1

**Comment by haikalpribadi** [comment]
Thank you, @hkuich !! :)
