### ISSUE TITLE
Write BDD test scenarios and documentation for GraqlUpdate

### ISSUE THREAD

**Issue by haikalpribadi** [graknlabs/graql#197]
## Problem to Solve

We have introduced a new Graql query: Graql Update. You can learn more about the grammar and implementation from this commit: https://github.com/graknlabs/graql/commit/d382cd5513b0c0d16f3dcf0de77d1cc1ece15693

## Proposed Solution

Please add a page to documentation, and add BDD scenarios to test this new query.

**Comment by haikalpribadi** [comment]
Moving this issue to graknlabs/grakn. Completing this issue means completing:

1) Implement BDD Scenarios to test Graql Update query
2) Implement BDD Steps in graknlabs/grakn to execute Graql Update scenarios
3) Implement BDD Steps in graknlabs/graql to execute Graql Update scenarios
4) Implement BDD Steps in graknlabs/client-java to execute Graql Update scenarios
5) Update documentation to describe Graql Update query

**Comment by flyingsilverfin** [comment]
@haikalpribadi i believe this is done right?

**Comment by haikalpribadi** [comment]
Yes I believe this is done, @flyingsilverfin. Will close it now.
