### ISSUE TITLE
Type labels allow more special characters

### ISSUE THREAD

**Issue by flyingsilverfin** [graknlabs/graql#202]
## Problem to Solve
To enable more auto-generated and auto-imported data sources, we can allow an extended set of special characters inside a type label. The currently allowed set only includes `-` and `_`. We propose adding the following list of special characters for non-starting characters in a label.
* `+`
* `/`
* `[`, `]`
* `(`, `)`

## Current Workaround

Applications have to use a special encoding mapping like `__leftsq__` to swap in and out `[`.

## Proposed Solution
Add the proposed list to the allowed set of characters in a type label.

**Comment by haikalpribadi** [comment]
Can you try submitting a PR for this, @flyingsilverfin? Let's see if it breaks anything in the grammar/parser.

**Comment by haikalpribadi** [comment]
I shall close this issue too @flyingsilverfin
