### ISSUE TITLE
Graql: Enable removing roleplayer from relationship in Graql

### ISSUE THREAD

**Issue by grabl** [graknlabs/graql#39]
This issue was originally posted by @haikalpribadi on 2017-08-30 12:26.

How can we remove a specific roleplayer from a relation? In the Java API, it could be as simple as:
```
relation.removeRolePlayer(instance);
```

But how do we do that with Graql? We have two options on the table:

Use a new keyword to flag the role player to be deleted:
```
match $r (actor NEW-KEYWORD $c: $x); $x isa person; delete $c;
```

Make the deletion part take in patterns:
```
match $r (actor: $x); $x isa person; delete $r (actor: $x);
```

Option 2 makes delete behave a lot like undefine which is nice but it may make get look like the odd one out. Insert and Delete take patterns but get only takes in a list of variables. Not sure how bad that is.

**Comment by haikalpribadi** [comment]
_This issue was originally posted by @jmsfltchr  on 2018-07-17 18:02_.

Presently there is no way in pure Graql to remove a roleplayer that is playing a role in a relationship. Currently the only way to effectively do this is to make a copy of the relationship with that roleplayer absent, and delete the original.

**Comment by haikalpribadi** [comment]
This issue has now been resolved with the new Delete query behaviour.
