### ISSUE TITLE
Graql: unable to match for presence of attribute without providing a variable for its value

### ISSUE THREAD

**Issue by grabl** [graknlabs/graql#41]
_This issue was originally posted by @jmsfltchr  on 2018-06-21 11:53_.

The following doesn't return all companies that have names: 
```
 match $x isa company has name; get; 
```
 What works is: 
```
 match $x isa company has name $y; get; 
```

**Comment by haikalpribadi** [comment]
I don't think this is a valid query we ever want to implement.
