### ISSUE TITLE
utf-8 support in Graql

### ISSUE THREAD

**Issue by kristall** [graknlabs/graql#58]
## Problem to Solve

At the moment Graql does not support utf-8 labels like  
`define Kläger sub entity;` or `define übermorgen sub relation;`  
but it'd be great if it would. This would allow non english "non-techies" a easier interaction when they trying to model with GraKn.

## Current Workaround

I'd would need to create an extra Layer in my NLP-Lib to change German Words that describe certain entities or relations to replace `äöüÄÖÜ` and `ß` with another representation. But it would highly decrease readbility and acceptance with my target audience.

## Proposed Solution

Support utf-8 as type labels (or in Graql in general)

**Comment by haikalpribadi** [comment]
This makes sense. I'll look into implementing this in the next release for Graql!

**Comment by flyingsilverfin** [comment]
Hi @kristall, I have had a quick look into this! The problem right now stems from our grammar only accepting the following regex for labels: `[a-zA-Z_] [a-zA-Z0-9_-]*` . I'll look into extending it to allow more diverse character sets. In the meantime I've found a fun workaround:

In all the grakn clients, you can define, retrieve, and create instances of types via a transaction *without* using `tx.query` or `tx.execute`. Using these methods will parse the passed strings via our grammar, which is what's causing errors. I actually have no problems doing the following in python:

```
In [24]: tx = s.transaction().write()

In [25]: t = tx.put_attribute_type("Özil", DataType.STRING)

In [26]: t.label()
Out[26]: 'Özil'

In [27]: inst = t.create(value="你好")

In [28]: tx.commit()

In [29]: tx = s.transaction().write()

In [34]: list(tx.query("match $x isa attribute; get;"))[0].get("x")
Out[34]: <grakn.service.Session.Concept.Concept.Attribute at 0x1069e9a20>

In [35]: list(tx.query("match $x isa attribute; get;"))[0].get("x").type().label()
Out[35]: 'Özil'

In [36]: list(tx.query("match $x isa attribute; get;"))[0].get("x").value()
Out[36]: '你好'
```

**Comment by flyingsilverfin** [comment]
Closed with https://github.com/graknlabs/graql/pull/59
